import { apiGet, apiPost, apiPatch, apiDelete, serviceCall, DEMO_MODE } from './api.js';
import { getState, updateState } from './mockStore.js';
import { normalizeCourses } from './dataAdapters.js';
export async function listCourses() { return serviceCall({ label: 'courses', api: async () => normalizeCourses(await apiGet('/courses')), mock: async () => normalizeCourses(getState().courses) }); }
export async function getCourse(id) { return serviceCall({ label: 'course', api: async () => normalizeCourses([await apiGet(`/courses/${id}`)])[0], mock: async () => normalizeCourses([getState().courses.find(c => c.id === id)])[0] }); }
export async function enrollCourse(id) { if (DEMO_MODE) { const courses=getState().courses.map(c=>c.id===id?{...c,enrolled:true,progress:c.progress||0}:c); updateState({courses}); return {data:normalizeCourses([courses.find(c=>c.id===id)])[0],source:'mock',message:'Course enrollment saved to demo data.'}; } return {data:normalizeCourses([await apiPost(`/courses/${id}/enroll`, {})])[0],source:'api',message:''}; }
export async function completeLesson(courseId, moduleId) { if (DEMO_MODE) { const courses=getState().courses.map(c=>{if(c.id!==courseId)return c;const modules=(c.modules||[]).map(m=>m.id===moduleId?{...m,done:true}:m);const done=modules.filter(m=>m.done).length;return {...c,modules,progress:Math.min(100,Math.max(c.progress||0,modules.length?Math.round(done/modules.length*100):0))};});updateState({courses});return {data:normalizeCourses([courses.find(c=>c.id===courseId)])[0],source:'mock',message:'Course progress saved to demo data.'}; } return {data:normalizeCourses([await apiPatch(`/courses/${courseId}/modules/${moduleId}`, { done: true })])[0],source:'api',message:''}; }
export async function createCourse(payload){ if(DEMO_MODE){const x={...payload,id:`c-${Date.now()}`,progress:0,enrolled:false};updateState({courses:[x,...getState().courses]});return {data:x,source:'mock',message:'Course created in demo data.'};}return {data:await apiPost('/courses',payload),source:'api',message:''}; }
export async function deleteCourse(id){ if(DEMO_MODE){updateState({courses:getState().courses.filter(c=>c.id!==id)});return {data:true,source:'mock',message:'Course deleted from demo data.'};}return {data:await apiDelete(`/courses/${id}`),source:'api',message:''}; }
