import { apiGet, apiPost, apiPut, serviceCall, DEMO_MODE } from './api.js';
import { getState, updateState } from './mockStore.js';
import { normalizeResources, normalizeTrainers, normalizeAssessmentResults } from './dataAdapters.js';
import { getSession } from './auth.js';
export async function getTrainerProfile(id=getSession()?.id||'u2'){return serviceCall({label:'trainer profile',api:async()=>await apiGet(`/trainers/${id}`),mock:async()=>({...JSON.parse(localStorage.getItem(`cc-trainer-profile-${id}`)||'null')||{},id,name:getSession()?.name||'Ananya Sharma',role:'trainer',specialization:'Web Development',skills:['HTML','CSS','JavaScript','React','Node.js']})});}
export async function updateTrainerProfile(payload,id=getSession()?.id||'u2'){if(DEMO_MODE){localStorage.setItem(`cc-trainer-profile-${id}`,JSON.stringify(payload));return {data:{...payload,id},source:'mock',message:'Trainer profile saved to demo data.'};}return {data:await apiPut(`/trainers/${id}`,payload),source:'api',message:''};}
export async function getTrainerResources(id=getSession()?.id||'u2'){return serviceCall({label:'trainer resources',api:async()=>normalizeResources(await apiGet(`/trainers/${id}/resources`)),mock:async()=>normalizeResources(getState().resources.filter(r=>r.trainerId===id||r.trainer==='Ananya Sharma'))});}
export async function getQuestionnaires(id=getSession()?.id||'u2'){return serviceCall({label:'questionnaires',api:async()=>await apiGet(`/trainers/${id}/questionnaires`),mock:async()=>{const seed=[{id:'q1',title:'Web Development Weekly Check',subject:'Web Development',deadline:'2026-09-18',questions:5,status:'Published',submissions:32},{id:'q2',title:'Cloud Basics Pulse Check',subject:'Cloud Computing',deadline:'2026-09-22',questions:8,status:'Draft',submissions:0}];try{return JSON.parse(localStorage.getItem('cc-questionnaires')||JSON.stringify(seed))}catch{return seed}}});}
export async function createQuestionnaire(payload,id=getSession()?.id||'u2'){if(DEMO_MODE){const items=JSON.parse(localStorage.getItem('cc-questionnaires')||'[]');const x={...payload,id:`q-${Date.now()}`};localStorage.setItem('cc-questionnaires',JSON.stringify([x,...items]));return {data:x,source:'mock',message:'Questionnaire saved to demo data.'};}return {data:await apiPost(`/trainers/${id}/questionnaires`,payload),source:'api',message:''};}
export async function getTraineePerformance(id=getSession()?.id||'u2'){return serviceCall({label:'trainer performance',api:async()=>await apiGet(`/trainers/${id}/performance`),mock:async()=>({subjects:[{subject:'Web',score:84},{subject:'Cloud',score:72},{subject:'Security',score:68},{subject:'AI',score:76}],submissions:normalizeAssessmentResults(getState().history)})});}
