import { useEffect,useState } from 'react';
import { AlertCircle,CheckCircle2,ChevronLeft,ChevronRight,RotateCcw } from 'lucide-react';
import { Link,useParams } from 'react-router-dom';
import PageHeader from '../components/PageHeader';
import ApiStatus from '../components/ApiStatus';
import { ErrorState,LoadingState } from '../components/LoadingState';
import { getAssessment,saveResult } from '../services/assessmentService';
export default function AssessmentWorkspace(){
 const {id}=useParams(); const [assessment,setAssessment]=useState(null),[idx,setIdx]=useState(0),[answers,setAnswers]=useState({}),[submitted,setSubmitted]=useState(false),[result,setResult]=useState(null),[loading,setLoading]=useState(true),[error,setError]=useState(''),[source,setSource]=useState('');
 async function load(){setLoading(true);setError('');try{const r=await getAssessment(id);setAssessment(r);setSource(r.source)}catch(e){setError(e.message)}finally{setLoading(false)}} useEffect(()=>{load()},[id]);
 if(loading)return <LoadingState message="Loading assessment…"/>; if(error)return <ErrorState message={error} onRetry={load}/>; const a=assessment?.data;if(!a)return <ErrorState message="Assessment not found."/>; const q=a.questionsData?.[idx];
 async function submit(){const correct=a.questionsData.reduce((n,x,i)=>n+(answers[i]===x.answer?1:0),0);const r={id:`h-${Date.now()}`,title:a.title,subject:a.subject,correct,total:a.questions,percentage:Math.round(correct/a.questions*100),at:new Date().toISOString()};try{const saved=await saveResult(r);setResult(saved.data);setSource(saved.source);setSubmitted(true)}catch(e){setError(e.message)}}
 if(submitted)return <div className="mx-auto max-w-4xl"><ApiStatus source={source} message={source==='mock'?'Assessment result is persisted in demo data.':''}/><PageHeader eyebrow="Assessment result" title={a.title} description="Your result is now available as competency evidence."/><div className="card mt-7 p-8 text-center"><div className="mx-auto grid h-20 w-20 place-items-center rounded-full bg-emerald-50 text-success"><CheckCircle2 size={42}/></div><div className="mt-5 text-5xl font-black text-navy">{result.percentage}%</div><p className="mt-2 font-bold">{result.correct} correct out of {result.total}</p><div className="mx-auto mt-5 max-w-sm rounded-xl bg-slate-50 p-4 text-sm text-slate-600">Performance level: <b>{result.percentage>=80?'Strong':result.percentage>=60?'Developing':'Needs improvement'}</b></div><div className="mt-7 flex justify-center gap-3"><button onClick={()=>{setSubmitted(false);setResult(null);setIdx(0);setAnswers({})}} className="btn-secondary"><RotateCcw size={16}/> Retry</button><Link to="/trainee/assessments" className="btn-primary">Back to assessments</Link></div></div><div className="card mt-6 p-6"><h2 className="font-black">Question review</h2><div className="mt-4 space-y-4">{a.questionsData.map((x,i)=><div className="rounded-xl border border-slate-200 p-4" key={`${x.q}-${i}`}><div className="text-sm font-bold">{i+1}. {x.q}</div><div className="mt-2 text-xs text-slate-500">Your answer: {x.options[answers[i]]||'Not answered'} • Correct: {x.options[x.answer]}</div></div>)}</div></div></div>;
 return <div className="mx-auto max-w-4xl"><ApiStatus source={source} message={source==='mock'?'Assessment content is using demo data.':''}/><PageHeader eyebrow={a.subject} title={a.title} description={`Question ${idx+1} of ${a.questions}`}/><div className="mt-7 card p-6 lg:p-8"><div className="flex items-center justify-between text-xs font-bold text-slate-500"><span>Progress</span><span>{Math.round((idx+1)/a.questions*100)}%</span></div><div className="mt-2 h-2 rounded-full bg-slate-100"><div className="h-full rounded-full bg-purple" style={{width:`${(idx+1)/a.questions*100}%`}}/></div><div className="mt-8 flex items-start gap-3"><AlertCircle className="mt-1 text-purple" size={20}/><h2 className="text-xl font-black leading-8">{q.q}</h2></div><div className="mt-7 grid gap-3">{q.options.map((opt,i)=><button key={opt} onClick={()=>setAnswers({...answers,[idx]:i})} className={`rounded-xl border p-4 text-left text-sm font-semibold transition ${answers[idx]===i?'border-purple bg-violet-50 text-purple':'border-slate-200 hover:bg-slate-50'}`}><span className="mr-3 inline-grid h-7 w-7 place-items-center rounded-full bg-slate-100 text-xs">{String.fromCharCode(65+i)}</span>{opt}</button>)}</div><div className="mt-8 flex justify-between"><button disabled={idx===0} onClick={()=>setIdx(idx-1)} className="btn-secondary disabled:opacity-40"><ChevronLeft size={17}/> Previous</button>{idx<a.questions-1?<button onClick={()=>setIdx(idx+1)} className="btn-primary">Next <ChevronRight size={17}/></button>:<button onClick={submit} disabled={Object.keys(answers).length!==a.questions} className="btn-primary disabled:opacity-40">Submit assessment</button>}</div></div></div>;
}
