import { useEffect, useMemo, useState } from 'react';
import { BookOpen, CheckCircle2, Search } from 'lucide-react';
import { Link } from 'react-router-dom';
import PageHeader from '../components/PageHeader';
import ApiStatus from '../components/ApiStatus';
import { EmptyState, ErrorState, LoadingState } from '../components/LoadingState';
import { listCourses, enrollCourse } from '../services/courseService';
export default function Courses(){
 const [result,setResult]=useState(null),[error,setError]=useState(''),[q,setQ]=useState(''),[category,setCategory]=useState('All'),[level,setLevel]=useState('All'),[busy,setBusy]=useState('');
 const load=async()=>{setError('');try{setResult(await listCourses())}catch(e){setError(e.message)}}; useEffect(()=>{load()},[]);
 const courses=result?.data||[]; const filtered=useMemo(()=>courses.filter(c=>(c.title+c.description+c.category).toLowerCase().includes(q.toLowerCase())&&(category==='All'||c.category===category)&&(level==='All'||c.level===level)),[courses,q,category,level]);
 async function enroll(id){setBusy(id);try{const r=await enrollCourse(id);setResult(prev=>({...prev,data:prev.data.map(c=>c.id===id?r.data:c)}));}catch(e){setError(e.message)}finally{setBusy('')}}
 if(error&&!result)return <div><PageHeader eyebrow="Learning" title="My courses" description="Discover courses, enroll, and build measurable learning progress."/><ErrorState message={error} onRetry={load}/></div>;
 if(!result)return <LoadingState message="Loading course catalog…"/>;
 const categories=['All',...new Set(courses.map(c=>c.category))];
 return <div className="mx-auto max-w-7xl"><PageHeader eyebrow="Learning" title="My courses" description="Discover courses, enroll, and build measurable learning progress."/><ApiStatus source={result.source} message={result.message}/><div className="flex flex-col gap-3 lg:flex-row"><div className="relative flex-1"><Search className="absolute left-4 top-3.5 text-slate-400" size={18}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search courses..." className="w-full rounded-xl border border-slate-200 bg-white py-3 pl-11 pr-4 outline-none"/></div><div className="flex gap-3"><select value={category} onChange={e=>setCategory(e.target.value)} className="rounded-xl border border-slate-200 bg-white px-4 text-sm"><option>All</option>{categories.slice(1).map(x=><option key={x}>{x}</option>)}</select><select value={level} onChange={e=>setLevel(e.target.value)} className="rounded-xl border border-slate-200 bg-white px-4 text-sm"><option>All</option><option>Beginner</option><option>Intermediate</option><option>Advanced</option></select></div></div><div className="mt-6 grid gap-5 md:grid-cols-2">{filtered.map(c=><article className="card p-6" key={c.id}><div className="flex items-start justify-between"><div className="grid h-11 w-11 place-items-center rounded-xl bg-blue-50 text-brand"><BookOpen/></div><span className="rounded-full bg-slate-100 px-3 py-1 text-xs font-bold">{c.level}</span></div><h2 className="mt-5 text-lg font-black">{c.title}</h2><p className="mt-2 text-sm leading-6 text-slate-500">{c.description}</p><div className="mt-4 text-xs font-semibold text-slate-500">{c.category} • {c.duration} • {c.trainer}</div><div className="mt-5 h-2 rounded-full bg-slate-100"><div className="h-full rounded-full bg-brand" style={{width:`${c.progress}%`}}/></div><div className="mt-2 flex justify-between text-xs font-bold text-slate-500"><span>{c.progress}% complete</span>{c.enrolled&&<span className="text-success">Enrolled</span>}</div><div className="mt-5 flex gap-2">{c.enrolled?<Link to={`/trainee/courses/${c.id}`} className="btn-primary flex-1">Continue</Link>:<button onClick={()=>enroll(c.id)} disabled={busy===c.id} className="btn-primary flex-1 disabled:opacity-60">{busy===c.id?'Enrolling…':'Enroll now'}</button>}<Link to={`/trainee/courses/${c.id}`} className="btn-secondary">Details</Link></div></article>)}{!filtered.length&&<div className="md:col-span-2"><EmptyState message="No courses match your filters."/></div>}</div>{error&&result&&<div className="mt-5 rounded-xl border border-red-200 bg-red-50 p-3 text-sm text-red-700">{error}</div>}</div>;
}
