import { BrainCircuit, BarChart3, ClipboardList, Settings } from 'lucide-react';
import { useEffect,useState } from 'react';
import PageHeader from '../components/PageHeader';
import ApiStatus from '../components/ApiStatus';
import { ErrorState,LoadingState } from '../components/LoadingState';
import { buildEngine } from '../services/competencyService';
export function AdminAssessments(){return <Generic icon={ClipboardList} title="Assessment management" text="Review subject assessments and participation. Assessment attempts are powered by the trainee assessment module."/>}
export function AdminCompetencies(){return <Generic icon={BrainCircuit} title="Competency management" text="Configure competency areas, target levels and evidence rules. The active competency insights page uses the same deterministic engine."/>}
export function AdminInsights(){const [d,setD]=useState(null),[error,setError]=useState('');const load=async()=>{try{setD(await buildEngine())}catch(e){setError(e.message)}};useEffect(()=>{load()},[]);if(error)return <ErrorState message={error} onRetry={load}/>;if(!d)return <LoadingState message="Loading admin competency insights…"/>;const avg=Math.round(d.competencyResults.reduce((a,b)=>a+b.score,0)/d.competencyResults.length);return <div className="mx-auto max-w-5xl"><ApiStatus source={d.source} message={d.message}/><PageHeader eyebrow="Administration" title="Admin insights" description="Aggregate prototype insights generated from the same rule-based competency data flow."/><div className="mt-7 grid gap-4 sm:grid-cols-3"><Stat label="Average competency" value={`${avg}%`}/><Stat label="Skill gaps" value={d.skillGaps.length}/><Stat label="Evidence categories" value="4"/></div><div className="card mt-6 p-6"><div className="flex items-center gap-3"><BarChart3 className="text-brand"/><div><h2 className="font-black">Competency summary</h2><p className="text-xs text-slate-500">Current trainee prototype profile</p></div></div><div className="mt-5 grid gap-3 md:grid-cols-2">{d.competencyResults.map(x=><div key={x.competencyId} className="flex items-center justify-between rounded-xl bg-slate-50 p-4"><span className="font-semibold">{x.competencyName}</span><b>{x.score}%</b></div>)}</div></div><div className="mt-5 rounded-xl border border-purple-100 bg-purple-50 p-5 text-sm text-purple-900">These are deterministic prototype insights, not predictive AI analytics.</div></div>}
export function AdminSettings(){return <Generic icon={Settings} title="Platform settings" text="Development settings are intentionally limited in this prototype. API configuration belongs in environment variables."/>}
function Generic({icon:Icon,title,text}){return <div className="mx-auto max-w-5xl"><PageHeader eyebrow="Administration" title={title} description={text}/><div className="card mt-7 p-8"><div className="grid h-14 w-14 place-items-center rounded-2xl bg-violet-50 text-purple"><Icon/></div><h2 className="mt-5 text-xl font-black">Module ready</h2><p className="mt-2 max-w-2xl text-sm leading-6 text-slate-500">This core module is connected to the admin navigation and shared service architecture.</p></div></div>}
function Stat({label,value}){return <div className="card p-5"><div className="text-xs font-bold uppercase tracking-wider text-slate-500">{label}</div><div className="mt-2 text-2xl font-black">{value}</div></div>}
