import { useEffect,useState } from 'react';
import { CheckCircle2,Save,UserRound } from 'lucide-react';
import PageHeader from '../components/PageHeader';
import ApiStatus from '../components/ApiStatus';
import { ErrorState,LoadingState } from '../components/LoadingState';
import { getSession } from '../services/auth';
import { getTrainerProfile,updateTrainerProfile } from '../services/trainerService';
const base={qualifications:'M.Tech in Computer Science',specialization:'Web Technologies & APIs',skills:'React, Node.js, REST APIs, JavaScript',experience:'6 years',certifications:'AWS Cloud Practitioner; Full Stack Professional',subjects:'Web Development, Cloud Computing',bio:'Technology trainer helping learners convert concepts into practical, job-ready skills.'};
export default function TrainerProfile(){const s=getSession();const [r,setR]=useState(null),[form,setForm]=useState(base),[saved,setSaved]=useState(false),[error,setError]=useState('');useEffect(()=>{getTrainerProfile(s?.id).then(x=>{setR(x);setForm({...base,...x.data,skills:Array.isArray(x.data?.skills)?x.data.skills.join(', '):x.data?.skills||base.skills})}).catch(e=>setError(e.message))},[s?.id]);async function save(e){e.preventDefault();try{const x=await updateTrainerProfile(form,s?.id);setR(x);setSaved(true);setTimeout(()=>setSaved(false),2000)}catch(e){setError(e.message)}}if(error&&!r)return <ErrorState message={error} onRetry={()=>window.location.reload()}/>;if(!r)return <LoadingState message="Loading trainer profile…"/>;return <div className="mx-auto max-w-6xl"><PageHeader eyebrow="Trainer profile" title="Professional trainer profile" description="Maintain the expertise information used for learner-to-trainer matching."/><ApiStatus source={r.source} message={r.message}/><form onSubmit={save} className="card mt-7 p-6 lg:p-8"><div className="flex items-center gap-4 border-b border-slate-100 pb-6"><div className="grid h-16 w-16 place-items-center rounded-full bg-violet-50 text-purple"><UserRound/></div><div><h2 className="font-black">{s.name}</h2><p className="text-sm text-slate-500">{s.email}</p></div></div><div className="mt-7 grid gap-5 sm:grid-cols-2">{Object.entries(form).filter(([k])=>k!=='bio').map(([name,value])=><label className="text-sm font-bold" key={name}>{name.replace(/([A-Z])/g,' $1').replace(/^./,x=>x.toUpperCase())}<input value={value||''} onChange={e=>setForm({...form,[name]:e.target.value})} className="mt-2 w-full rounded-xl border border-slate-200 px-4 py-3 font-normal outline-none focus:border-brand"/></label>)}<label className="text-sm font-bold sm:col-span-2">Bio<textarea rows="4" value={form.bio||''} onChange={e=>setForm({...form,bio:e.target.value})} className="mt-2 w-full rounded-xl border border-slate-200 px-4 py-3 font-normal"/></label></div><div className="mt-7 flex justify-end gap-3">{saved&&<span className="flex items-center gap-2 text-sm font-bold text-success"><CheckCircle2 size={16}/> Saved</span>}<button className="btn-primary"><Save size={16}/> Save profile</button></div>{error&&<p className="mt-3 text-sm text-red-600">{error}</p>}</form></div>}
