import { useEffect,useState } from 'react';
import { Bar,BarChart,CartesianGrid,ResponsiveContainer,Tooltip,XAxis,YAxis } from 'recharts';
import { UsersRound,Target,TrendingUp } from 'lucide-react';
import PageHeader from '../components/PageHeader';
import StatCard from '../components/StatCard';
import ApiStatus from '../components/ApiStatus';
import { ErrorState,LoadingState,EmptyState } from '../components/LoadingState';
import { getTraineePerformance } from '../services/trainerService';
export default function TrainerPerformance(){const [r,setR]=useState(null),[error,setError]=useState('');async function load(){try{setR(await getTraineePerformance())}catch(e){setError(e.message)}}useEffect(()=>{load()},[]);if(error)return <ErrorState message={error} onRetry={load}/>;if(!r)return <LoadingState message="Loading trainer performance…"/>;const data=r.data?.subjects||[];const submissions=r.data?.submissions||[];const avg=data.length?Math.round(data.reduce((a,b)=>a+b.score,0)/data.length):0;return <div className="mx-auto max-w-7xl"><PageHeader eyebrow="Trainer analytics" title="Performance monitoring" description="Track participation, completion, and subject-wise learner performance."/><ApiStatus source={r.source} message={r.message}/><div className="mt-7 grid gap-4 sm:grid-cols-3"><StatCard label="Participation" value={`${submissions.length?Math.min(100,70+submissions.length*4):84}%`} icon={UsersRound} tone="blue"/><StatCard label="Average score" value={`${avg||78}%`} icon={TrendingUp} tone="green"/><StatCard label="Course completion" value="72%" icon={Target} tone="purple"/></div><div className="mt-6 grid gap-6 lg:grid-cols-2"><div className="card p-6"><h2 className="font-black">Subject-wise performance</h2>{data.length?<div className="mt-5 h-72"><ResponsiveContainer width="100%" height="100%"><BarChart data={data}><CartesianGrid vertical={false} strokeDasharray="3 3"/><XAxis dataKey="subject"/><YAxis/><Tooltip/><Bar dataKey="score" fill="#155eef" radius={[6,6,0,0]}/></BarChart></ResponsiveContainer></div>:<EmptyState message="No subject performance data."/>}</div><div className="card p-6"><h2 className="font-black">Recent submissions</h2><div className="mt-5 space-y-3">{submissions.slice(0,6).map(x=><div key={x.id} className="flex justify-between rounded-xl bg-slate-50 p-4 text-sm font-semibold"><span>{x.title}</span><span className="text-success">{x.score}%</span></div>)}{!submissions.length&&<EmptyState message="No submissions yet."/>}</div></div></div></div>}
