import { useEffect, useMemo, useState } from 'react';
import { BrainCircuit, RefreshCw, ShieldCheck, Target } from 'lucide-react';
import PageHeader from '../../components/PageHeader';
import CompetencyCard from '../../components/competency/CompetencyCard';
import SkillGapCard from '../../components/competency/SkillGapCard';
import RecommendationCard from '../../components/competency/RecommendationCard';
import TrainerMatchCard from '../../components/competency/TrainerMatchCard';
import WeightedScoreBreakdown from '../../components/competency/WeightedScoreBreakdown';
import ApiStatus from '../../components/ApiStatus';
import { ErrorState } from '../../components/LoadingState';
import { buildEngine } from '../../services/competencyService';
import { generateRecommendations } from '../../services/recommendationService';
import { matchTrainers } from '../../services/trainerMatchingService';
import { getSession } from '../../services/auth';
import { competencyRequirements } from '../../data/competencyRules';

export default function CompetencyPage(){
 const session=getSession(); const [targetId,setTargetId]=useState(competencyRequirements[0].id); const [data,setData]=useState(null); const [error,setError]=useState('');
 const load=async()=>{setError('');try{setData(await buildEngine(session?.id||'u1',targetId));}catch(e){setData(null);setError(e.message||'Unable to calculate competency.');}};
 useEffect(()=>{load()},[targetId]);
 const recs=useMemo(()=>data?generateRecommendations(data.skillGaps,data.courses,data.resources):[],[data]);
 const matches=useMemo(()=>data?matchTrainers(data.skillGaps,data.trainers):[],[data]);
 if(!data&&error)return <div><PageHeader eyebrow="Competency Engine" title="Unable to load competency evidence" description="The engine needs profile, assessment, course, certificate and trainer data before it can calculate a score."/><ErrorState message={error} onRetry={load}/></div>;
 if(!data)return <div><PageHeader eyebrow="Competency Engine" title="Evidence-based skill intelligence" description="Calculating a transparent competency profile from your learning evidence."/><div className="card p-10 text-center"><RefreshCw className="mx-auto animate-spin text-brand"/><p className="mt-3 text-sm text-slate-500">Processing profile, assessments and course evidence…</p>{error&&<p className="mt-2 text-sm text-red-600">{error}</p>}</div></div>;
 const high=data.skillGaps.filter(g=>g.priority==='High').length;
 return <div className="space-y-7"><ApiStatus source={data.source} message={data.message}/><PageHeader eyebrow="Competency Engine" title="Understand where your skills stand" description="A deterministic, explainable assessment of competency built from your profile and learning evidence." actions={<div className="flex gap-2"><select value={targetId} onChange={e=>setTargetId(e.target.value)} className="rounded-xl border border-slate-200 bg-white px-3 py-2.5 text-sm font-semibold">{data.competencies.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select><button onClick={load} className="btn-secondary"><RefreshCw size={16}/> Recalculate</button></div>}/>
 <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><Summary icon={BrainCircuit} label="Overall score" value={`${data.targetResult.score}%`} sub={data.targetResult.level}/><Summary icon={Target} label="Strongest competency" value={data.competencyResults.reduce((a,b)=>a.score>b.score?a:b).competencyName} sub="Highest calculated score"/><Summary icon={ShieldCheck} label="High priority gaps" value={high} sub="Need focused improvement"/><Summary icon={Target} label="Recommendations" value={recs.length} sub="Explainable next steps"/></div>
 <section><div className="mb-4"><h2 className="text-xl font-bold">Competency overview</h2><p className="text-sm text-slate-500">Select a competency to understand the score and evidence behind it.</p></div><div className="grid gap-4 md:grid-cols-2">{data.competencyResults.map(item=><CompetencyCard key={item.competencyId} item={item} onView={()=>{setTargetId(item.competencyId);window.scrollTo({top:0,behavior:'smooth'})}}/>)}</div></section>
 <div className="grid gap-6 lg:grid-cols-2"><WeightedScoreBreakdown result={data.targetResult}/><div className="card p-5"><div className="eyebrow">Evidence used</div><h2 className="mt-1 text-lg font-bold">Why this score?</h2><div className="mt-4 grid grid-cols-2 gap-3">{Object.entries(data.targetResult.evidence).map(([k,v])=><div key={k} className="rounded-xl bg-slate-50 p-3"><div className="text-xs capitalize text-slate-500">{k}</div><div className="mt-1 font-bold">{typeof v==='boolean'?(v?'Available':'Not available'):v}</div></div>)}</div><p className="mt-4 text-xs leading-5 text-slate-500">This score is calculated using predefined rules and weighted evidence. It is not generated by a machine learning model. Missing evidence contributes a score of 0 for that evidence category.</p></div></div>
 <section><div className="mb-4"><h2 className="text-xl font-bold">Skill gaps</h2><p className="text-sm text-slate-500">Target: {data.target.name}. Gaps are ranked by the size of the difference between current and required skill level.</p></div>{data.skillGaps.length?<div className="grid gap-4 md:grid-cols-2">{data.skillGaps.map(g=><SkillGapCard key={g.skill} gap={g}/>)}</div>:<div className="card p-8 text-center text-sm text-green-700">Great work — no skill gaps were detected for this target.</div>}</section>
 <section><div className="mb-4"><h2 className="text-xl font-bold">Recommended learning path</h2><p className="text-sm text-slate-500">Recommendations are derived from detected gaps and related demo course/resource metadata.</p></div>{recs.length?<div className="grid gap-4 md:grid-cols-2">{recs.map(r=><RecommendationCard key={r.id} item={r}/>)}</div>:<div className="card p-8 text-center text-sm text-slate-500">No matching demo courses or resources were found.</div>}</section>
 <section><div className="mb-4"><h2 className="text-xl font-bold">Trainer matches</h2><p className="text-sm text-slate-500">Prototype matching only — this does not represent an official trainer assignment.</p></div>{matches.length?<div className="grid gap-4 md:grid-cols-2">{matches.slice(0,4).map(t=><TrainerMatchCard key={t.id} trainer={t}/>)}</div>:<div className="card p-8 text-center text-sm text-slate-500">No trainer has a direct match for the detected gaps.</div>}</section>
 </div>
}
function Summary({icon:Icon,label,value,sub}){return <div className="card p-5"><div className="flex items-center gap-3"><div className="grid h-10 w-10 place-items-center rounded-xl bg-purple-50 text-purple-600"><Icon size={19}/></div><span className="text-xs font-bold uppercase tracking-wider text-slate-500">{label}</span></div><div className="mt-4 truncate text-2xl font-black text-slate-900">{value}</div><div className="mt-1 text-xs text-slate-500">{sub}</div></div>}
