import { BarChart3, Bell, BookOpen, BrainCircuit, ChevronRight, FileCheck2, FileText, LayoutDashboard, LogOut, Menu, Settings, ShieldCheck, UserRound, UsersRound, X, Award, ClipboardList } from 'lucide-react';
import { NavLink, Outlet, useNavigate } from 'react-router-dom';
import { useState } from 'react';
import Logo from '../components/Logo';
import { getSession } from '../services/auth';
import { logout } from '../services/authService';

const menus={trainee:[['/trainee/dashboard','Dashboard',LayoutDashboard],['/trainee/profile','My Profile',UserRound],['/trainee/courses','Courses',BookOpen],['/trainee/resources','Resources',FileText],['/trainee/competency','Competency Engine',BrainCircuit],['/trainee/competency-passport','Competency Passport',ShieldCheck],['/trainee/assessments','Assessments',FileCheck2],['/trainee/notifications','Notifications',Bell]],trainer:[['/trainer/dashboard','Dashboard',LayoutDashboard],['/trainer/profile','My Profile',UserRound],['/trainer/library','Trainer Library',FileText],['/trainer/questionnaires','Questionnaires',ClipboardList],['/trainer/performance','Performance',BarChart3],['/trainer/notifications','Notifications',Bell]],admin:[['/admin/dashboard','Dashboard',LayoutDashboard],['/admin/users','User Management',UsersRound],['/admin/courses','Course Management',BookOpen],['/admin/resources','Resources',FileText],['/admin/assessments','Assessments',FileCheck2],['/admin/certificates','Certifications',Award],['/admin/announcements','Announcements',Bell],['/admin/competencies','Competencies',BrainCircuit],['/admin/insights','Insights',BarChart3],['/admin/settings','Settings',Settings]]};
export default function DashboardLayout(){const [open,setOpen]=useState(false);const nav=useNavigate();const session=getSession();const items=menus[session.role];async function handleLogout(){await logout();nav('/login',{replace:true});}return <div className="min-h-screen bg-[#f5f7fb]"><aside className={`fixed inset-y-0 left-0 z-40 w-72 border-r border-slate-200 bg-white p-5 transition-transform lg:translate-x-0 ${open?'translate-x-0':'-translate-x-full'}`}><div className="flex items-center justify-between"><Logo/><button onClick={()=>setOpen(false)} className="lg:hidden"><X/></button></div><div className="mt-8 rounded-2xl bg-slate-50 p-4"><div className="flex items-center gap-3"><div className="grid h-10 w-10 place-items-center rounded-full bg-navy font-bold uppercase text-white">{session.name.split(' ').map(x=>x[0]).slice(0,2).join('')}</div><div className="min-w-0"><div className="truncate text-sm font-bold">{session.name}</div><div className="text-xs capitalize text-slate-500">{session.role}</div></div></div></div><nav className="mt-6 space-y-1 overflow-y-auto pb-20">{items.map(([to,label,Icon])=><NavLink key={to} to={to} onClick={()=>setOpen(false)} className={({isActive})=>`flex items-center gap-3 rounded-xl px-3 py-3 text-sm font-semibold ${isActive?'bg-blue-50 text-brand':'text-slate-600 hover:bg-slate-50'}`}><Icon size={18}/>{label}<ChevronRight size={15} className="ml-auto opacity-40"/></NavLink>)}</nav><div className="absolute bottom-5 left-5 right-5"><button onClick={handleLogout} className="flex w-full items-center gap-3 rounded-xl px-3 py-3 text-sm font-semibold text-slate-500 hover:bg-slate-50"><LogOut size={18}/> Logout</button></div></aside><div className="lg:pl-72"><header className="sticky top-0 z-30 flex h-16 items-center justify-between border-b border-slate-200 bg-white/95 px-5 backdrop-blur lg:px-8"><button className="lg:hidden" onClick={()=>setOpen(true)}><Menu/></button><div className="hidden lg:block"><p className="text-sm font-semibold text-slate-500">{session.role.charAt(0).toUpperCase()+session.role.slice(1)} workspace</p></div><div className="flex items-center gap-3"><button className="rounded-xl p-2 text-slate-500 hover:bg-slate-50"><Settings size={19}/></button><div className="grid h-9 w-9 place-items-center rounded-full bg-slate-200 text-xs font-black uppercase">{session.name.split(' ').map(x=>x[0]).slice(0,2).join('')}</div></div></header><main className="p-5 lg:p-8"><Outlet/></main></div></div>}
